version: '3'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:latest
    container_name: datalowe-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    # // uncomment if you want to be able to interact with the
    # // postgreSQL database directly from host (using e.g. `psql`)
    # ports:
    #   - "5432:5432"
  backend:
    build: .
    container_name: datalowe-backend
    ports:
      - "8080:8080"
    environment:
      DB_DOMAIN: datalowe-postgres
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASSWORD: devpass
    depends_on:
      - postgres